apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-rest-api
  labels:
    app: go-rest-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-rest-api
  template:
    metadata:
      labels:
        app: go-rest-api
    spec:
      containers:
      - name: go-rest-api
        image: go-rest-api:v0.0.01
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: go-rest-api
spec:
  selector:
    app: go-rest-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  clusterIP: 10.96.1.1
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.1.11