pipeline {
    agent any
    environment {
        DOCKER_IMAGE = "pankaj91as/go-rest-api"
        DOCKER_REGISTRY_CREDENTIALS = 'dockerhub_credentials'
        BUILD_NUMBER = 'latest'
    }
    stages {
        stage('Checkout') {
            steps {
                // Checkout code from Development branch
                git branch: 'main', url: 'https://github.com/pankaj91as/GO-Rest-API.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    // Build Docker image
                    sh 'docker build -t ${DOCKER_IMAGE}:${BUILD_NUMBER} .'
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    // Log in to DockerHub
                    withCredentials([usernamePassword(credentialsId: "${DOCKER_REGISTRY_CREDENTIALS}", passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                        sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
                    }
                    // Push Docker image to DockerHub
                    sh 'docker push ${DOCKER_IMAGE}:${BUILD_NUMBER}'
                }
            }
        }
    }
    post {
        always {
            // Clean up workspace and Docker images
            sh 'docker rmi ${DOCKER_IMAGE}:${BUILD_NUMBER}'
            cleanWs()
        }
    }
}
