apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-rest-api-deployment
  labels:
    app: go-rest-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-rest-api
  template:
    metadata:
      labels:
        app: go-rest-api
    spec:
      containers:
      - name: go-rest-api
        image: go-rest-api:v1.0
        ports:
        - containerPort: 8080
