apiVersion: v1
kind: Service
metadata:
  name: go-rest-api
spec:
  selector:
    app: go-rest-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  clusterIP: 10.96.1.1
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.1.11